### ISSUE TITLE
Issues with README

### ISSUE THREAD

**Issue by jbrucker** [patdpat/django-polls#2]
Python 3.6.6 - too specific?  Will it run with any Python 3.6?

Django 2.2.5 - too specific?  This is actually redundant requirement, since it is in requirements.txt

requirements.txt - contain a lot dependencies.  Are they needed?
Your instructions don't specify creating a virtualenv, so why does
user need the virtualenv packages?   I think some others aren't
needed as well.

When I follow the instructions exactly, the web browser shows:
    OperationError

the web page is attached
[OperationalError.pdf](https://github.com/patdpat/django-polls/files/3638501/OperationalError.pdf)

**Comment by patdpat** [comment]
Hi, Pat here
Thanks for report the issues.
I've just found out that virtualenv slip into requirements.txt by cli called write-depe.
However, I managed to remove it from requirements.txt, and also updated readme.
You clearly have a point. I took some time and reviewed your request.

What I've done.
1. Remove Pollutions from requirements.txt
2. Update Requirement in README.md
3. Update Instruction in README.md
[new README.md](https://github.com/patdpat/django-polls/blob/master/README.md)
