### ISSUE TITLE
Issues with README

### ISSUE THREAD

**Issue by SukritaEarn** [patdpat/django-polls#3]
When I follow the instructions how to run this project, i successfully access to this web browser. 
-> http://localhost:8000/
Then I click "To Polls" and it goes to http://localhost:8000/polls/ , but this web browser shows :
"No polls are available."
<img width="1440" alt="localhost_polls" src="https://user-images.githubusercontent.com/48820434/65495971-cd025200-dee1-11e9-8355-391e64d087f9.png">

**Comment by patdpat** [comment]
I'll review this later.

**Comment by patdpat** [comment]
@SukritaEarn  I've just add how to add polls in the instruction please check and review :D

**Comment by SukritaEarn** [comment]
I think everything is working fine right now. Thank you for your consideration and response. 🙇‍♀

**Comment by SukritaEarn** [comment]
I think everything is working properly right now. Thank you for your consideration and response. 🙇‍♀
