### ISSUE TITLE
Issue with word

### ISSUE THREAD

**Issue by SukritaEarn** [patdpat/django-polls#5]
I think "Just Kidding :P" is not suitable to write in README.
You should use "Do not take it seriously 😜"

OR

Remove these 3 line:

For Window user go get Macintosh, or unix-like machine from your local computer store.
Just Kidding :P
use python manage.py migrateat step 4. then python manage.py runserverat step 5.

because you already have steps that state those methods.

PS. I'm just kidding with the first method that I suggest, You should just remove those 3 lines.
If it is not necessary.

**Comment by patdpat** [comment]
Removed
